version: '3.8'
services:
    ifcjson:
        container_name: ifcjson
        build:
          context: .
          dockerfile: ./Dockerfile
        ports:
            - "8000:8000"
        tty: true
        volumes:
          - .:/code/
          - ${PIP_CACHE_DIR_DETECTION:-cache-detection}:/root/.cache

volumes:
  cache-detection:


